services:
  - type: web
    name: solution-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    envVars: []
    plan: free

  - type: web
    name: solution-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    autoDeploy: true
    plan: free
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: https://solution-backend.onrender.com
